#!/usr/bin/env python3
"""Generate SendOamTest.bas with fresh per-exception approve/flag tokens baked in.

Run from the repo root:

    uv run python tests/generate-oam-test-bas.py \
        --originator <YOUR-OAM-GUID> \
        --approver james.nguyen@microsoft.com \
        --recipient admin@MngEnvMCAP683110.onmicrosoft.com

This writes tests/SendOamTest.bas which you import into Outlook VBA and run.
"""
from __future__ import annotations
import argparse
import json
import os
import sys
from pathlib import Path

# Allow running from anywhere
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.common.tokens import mint  # noqa: E402

BASE_URL = "https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io"

# The two demo exceptions (must match seed in mock_data/exceptions.json).
EXCEPTIONS = [
    {
        "id": "EXC-2026-05B-001",
        "employee_name": "Joseph Smith",
        "title": "Overtime variance high",
        "summary": "EXC-2026-05B-001 - 14.5h OT vs 4h avg (261% over 6 periods). Impact $847.50.",
        "style": "warning",
    },
    {
        "id": "EXC-2026-05B-002",
        "employee_name": "Sarah Lee",
        "title": "PTO missing manager approval",
        "summary": "EXC-2026-05B-002 - 3 days PTO 2026-05-25..27, no approver action. Impact $1,240.00.",
        "style": "accent",
    },
]


def url_for(verb: str, approver: str, exc_id: str, batch_id: str) -> str:
    token = mint(
        purpose=verb,  # approve_exception | flag_exception
        subject=approver,
        extra={"exception_id": exc_id, "batch_id": batch_id, "via": "oam"},
        ttl_seconds=86400,
    )
    endpoint = "approve-exception" if verb == "approve_exception" else "flag-exception"
    return f"{BASE_URL}/cta/{endpoint}?token={token}"


def card_dict(originator: str, approver: str) -> dict:
    batch_id = "BATCH-2026-05B"
    body: list[dict] = [
        {"type": "TextBlock", "text": "Payroll exceptions need your review",
         "size": "Large", "weight": "Bolder", "wrap": True},
        {"type": "TextBlock", "text": "Acme Manufacturing - Pay period ending May 30, 2026",
         "isSubtle": True, "wrap": True, "spacing": "None"},
        {"type": "FactSet", "spacing": "Medium", "facts": [
            {"title": "Cycle", "value": "Pay period ending May 30, 2026"},
            {"title": "Deadline", "value": "2026-05-30 17:00 PT"},
            {"title": "Open exceptions", "value": str(len(EXCEPTIONS))},
            {"title": "Estimated impact", "value": "$2,087.50"},
        ]},
    ]
    for exc in EXCEPTIONS:
        body.append({
            "type": "Container",
            "style": exc["style"],
            "spacing": "Medium",
            "items": [
                {"type": "TextBlock", "text": f"{exc['employee_name']} - {exc['title']}",
                 "weight": "Bolder", "wrap": True},
                {"type": "TextBlock", "text": exc["summary"], "wrap": True, "spacing": "Small"},
                {"type": "ActionSet", "spacing": "Small", "actions": [
                    {"type": "Action.OpenUrl", "title": "✅ Approve",
                     "url": url_for("approve_exception", approver, exc["id"], batch_id)},
                    {"type": "Action.OpenUrl", "title": "🚩 Flag for HR",
                     "url": url_for("flag_exception", approver, exc["id"], batch_id)},
                ]},
            ],
        })
    return {
        "type": "AdaptiveCard",
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.5",
        "originator": originator,
        "hideOriginalBody": False,
        "body": body,
        "actions": [
            {"type": "Action.OpenUrl",
             "title": "Review with PayCycle Assistant",
             "url": f"{BASE_URL}/cta/handoff?token={mint('handoff', approver, {'persona':'payroll_admin','batch_id':batch_id,'intent':'review_exceptions','event':'alert/CYC-2026-05B','exception_ids':[e['id'] for e in EXCEPTIONS]}, 86400)}&surface=teams"},
        ],
    }


def vba_escape(s: str) -> str:
    """Escape a string for VBA: double quotes become double-double quotes."""
    return s.replace('"', '""')


def chunks(s: str, n: int):
    for i in range(0, len(s), n):
        yield s[i:i + n]


def build_bas(card_json: str, recipient: str) -> str:
    # Break the card JSON into ~180-char chunks and emit them as
    # `cj = cj & "..."` so we stay way under VBA's continuation cap.
    lines = []
    lines.append('cj = ""')
    for chunk in chunks(card_json, 180):
        lines.append(f'    cj = cj & "{vba_escape(chunk)}"')
    cj_body = "\n".join(lines)

    return f"""Attribute VB_Name = "SendOamTest"
' Auto-generated by tests/generate-oam-test-bas.py
' Per-row Approve / Flag buttons + footer "Review with PayCycle Assistant".
'
' Import: Outlook -> Alt+F11 -> File > Import File... > SendOamTest.bas
' Run:    Place cursor in SendOamTest, press F5.

Option Explicit

Public Sub SendOamTest()
    Const RECIPIENT As String = "{vba_escape(recipient)}"
    Const SUBJ      As String = "PayCycle OAM test - per-row Approve / Flag actions"

    Dim cj As String
{cj_body}

    Dim html As String
    html = "<!DOCTYPE html><html><head><meta charset=""utf-8"">"
    html = html & "<script type=""application/adaptivecard+json"">" & vbCrLf
    html = html & cj & vbCrLf
    html = html & "</script>"
    html = html & "</head><body style=""font-family:Segoe UI,Arial,sans-serif;max-width:600px;color:#222"">"
    html = html & "<h2 style=""color:#c43d3d"">Payroll exceptions need your review</h2>"
    html = html & "<p>Acme Manufacturing - Pay period ending May 30, 2026 - 2 open exceptions, est. impact $2,087.50</p>"
    html = html & "<ul>"
    html = html & "<li><b>Joseph Smith</b> - Overtime variance high ($847.50)</li>"
    html = html & "<li><b>Sarah Lee</b> - PTO missing manager approval ($1,240.00)</li>"
    html = html & "</ul>"
    html = html & "<p><em>If your client does not render the Adaptive Card above, use the link below.</em></p>"
    html = html & "</body></html>"

    Dim msg As Outlook.MailItem
    Set msg = Application.CreateItem(olMailItem)
    msg.To = RECIPIENT
    msg.Subject = SUBJ
    msg.HTMLBody = html
    msg.Send

    MsgBox "Sent OAM test to " & RECIPIENT, vbInformation, "PayCycle"
End Sub
"""


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--originator", required=True, help="OAM originator GUID from the dashboard")
    p.add_argument("--approver", default="james.nguyen@microsoft.com",
                   help="Email subject for the signed tokens (becomes the approver/actor in audit)")
    p.add_argument("--recipient", default="admin@MngEnvMCAP683110.onmicrosoft.com",
                   help="Recipient mailbox")
    p.add_argument("--out", default=str(Path(__file__).resolve().parent / "SendOamTest.bas"))
    args = p.parse_args()

    card = card_dict(args.originator, args.approver)
    card_json = json.dumps(card, separators=(",", ":"))
    bas = build_bas(card_json, args.recipient)

    out_path = Path(args.out)
    out_path.write_text(bas, encoding="utf-8")
    print(f"Wrote {out_path}  ({len(bas):,} bytes)")
    print(f"Card JSON length: {len(card_json):,} chars")
    print("Next: in Outlook -> Alt+F11 -> Remove old SendOamTest -> File > Import File... -> pick the .bas -> F5")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
