Attribute VB_Name = "SendOamTest"
' Auto-generated by tests/generate-oam-test-bas.py
' Per-row Approve / Flag buttons + footer "Review with PayCycle Assistant".
'
' Import: Outlook -> Alt+F11 -> File > Import File... > SendOamTest.bas
' Run:    Place cursor in SendOamTest, press F5.

Option Explicit

Public Sub SendOamTest()
    Const RECIPIENT As String = "admin@MngEnvMCAP683110.onmicrosoft.com"
    Const SUBJ      As String = "PayCycle OAM test - per-row Approve / Flag actions"

    Dim cj As String
cj = ""
    cj = cj & "{""type"":""AdaptiveCard"",""$schema"":""http://adaptivecards.io/schemas/adaptive-card.json"",""version"":""1.5"",""originator"":""REPLACE-WITH-YOUR-GUID"",""hideOriginalBody"":false,""body"":[{""type"""
    cj = cj & ":""TextBlock"",""text"":""Payroll exceptions need your review"",""size"":""Large"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""Acme Manufacturing - Pay period ending May 30, 2"
    cj = cj & "026"",""isSubtle"":true,""wrap"":true,""spacing"":""None""},{""type"":""FactSet"",""spacing"":""Medium"",""facts"":[{""title"":""Cycle"",""value"":""Pay period ending May 30, 2026""},{""title"":""Deadline"",""val"
    cj = cj & "ue"":""2026-05-30 17:00 PT""},{""title"":""Open exceptions"",""value"":""2""},{""title"":""Estimated impact"",""value"":""$2,087.50""}]},{""type"":""Container"",""style"":""warning"",""spacing"":""Medium"",""item"
    cj = cj & "s"":[{""type"":""TextBlock"",""text"":""Joseph Smith - Overtime variance high"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""EXC-2026-05B-001 - 14.5h OT vs 4h avg (261% over 6"
    cj = cj & " periods). Impact $847.50."",""wrap"":true,""spacing"":""Small""},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.OpenUrl"",""title"":""\u2705 Approve"",""url"":""https://payroll"
    cj = cj & "-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/approve-exception?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiYXBwcm92ZV9leGNlcHRpb24iLCJzdWIiOiJq"
    cj = cj & "YW1lcy5uZ3V5ZW5AbWljcm9zb2Z0LmNvbSIsImlhdCI6MTc3OTE1MDMzNSwiZXhwIjoxNzc5MjM2NzM1LCJqdGkiOiIxZjI4MzI5Yy1hYjEzLTRiYWYtOTRkOS01MjQxNDc3ZmQyZTciLCJleGNlcHRpb25faWQiOiJFWEMtMjAyNi0wNUIt"
    cj = cj & "MDAxIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsInZpYSI6Im9hbSJ9.iGcjVYH_UgRQPFLO0OEIR94-S2SyTO2JSbVmKEtDF6U""},{""type"":""Action.OpenUrl"",""title"":""\ud83d\udea9 Flag for HR"",""url"":""https:"
    cj = cj & "//payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/flag-exception?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiZmxhZ19leGNlcHRpb24iLCJzdWIiOi"
    cj = cj & "JqYW1lcy5uZ3V5ZW5AbWljcm9zb2Z0LmNvbSIsImlhdCI6MTc3OTE1MDMzNSwiZXhwIjoxNzc5MjM2NzM1LCJqdGkiOiJjNjExM2I1MS01MDllLTQ1NmItODQxOS0zNjg4ZDUzZGFlMjYiLCJleGNlcHRpb25faWQiOiJFWEMtMjAyNi0wNU"
    cj = cj & "ItMDAxIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsInZpYSI6Im9hbSJ9.SwuN-2mv-ywEbO3DLaUcQXm_qH3yaG7rdny28RpSOpU""}]}]},{""type"":""Container"",""style"":""accent"",""spacing"":""Medium"",""items"":[{"""
    cj = cj & "type"":""TextBlock"",""text"":""Sarah Lee - PTO missing manager approval"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""EXC-2026-05B-002 - 3 days PTO 2026-05-25..27, no appr"
    cj = cj & "over action. Impact $1,240.00."",""wrap"":true,""spacing"":""Small""},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.OpenUrl"",""title"":""\u2705 Approve"",""url"":""https://pay"
    cj = cj & "roll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/approve-exception?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiYXBwcm92ZV9leGNlcHRpb24iLCJzdWIi"
    cj = cj & "OiJqYW1lcy5uZ3V5ZW5AbWljcm9zb2Z0LmNvbSIsImlhdCI6MTc3OTE1MDMzNSwiZXhwIjoxNzc5MjM2NzM1LCJqdGkiOiIxZjVjMGRkYy1kZTQxLTRkZjItYTc5Yi0yZDAyM2YxNDI2YTIiLCJleGNlcHRpb25faWQiOiJFWEMtMjAyNi0w"
    cj = cj & "NUItMDAyIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsInZpYSI6Im9hbSJ9.LNj808D4rtEMkASjm2MWj-o9-W0g9QJuGeUve71I6XI""},{""type"":""Action.OpenUrl"",""title"":""\ud83d\udea9 Flag for HR"",""url"":""ht"
    cj = cj & "tps://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/flag-exception?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiZmxhZ19leGNlcHRpb24iLCJzdW"
    cj = cj & "IiOiJqYW1lcy5uZ3V5ZW5AbWljcm9zb2Z0LmNvbSIsImlhdCI6MTc3OTE1MDMzNSwiZXhwIjoxNzc5MjM2NzM1LCJqdGkiOiIzNGM1MGY2ZS1lMjYwLTQ5YmQtYTQ2Yy05OTA5YjcwMGRkOTAiLCJleGNlcHRpb25faWQiOiJFWEMtMjAyNi"
    cj = cj & "0wNUItMDAyIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsInZpYSI6Im9hbSJ9.2gu-yW-5qdAuQmIeEkBWwYUymR4Yb0oFsgty3axbAM8""}]}]}],""actions"":[{""type"":""Action.OpenUrl"",""title"":""Review with PayCy"
    cj = cj & "cle Assistant"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/handoff?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiaGFuZG9mZ"
    cj = cj & "iIsInN1YiI6ImphbWVzLm5ndXllbkBtaWNyb3NvZnQuY29tIiwiaWF0IjoxNzc5MTUwMzM1LCJleHAiOjE3NzkyMzY3MzUsImp0aSI6IjMyZTFlNDBmLWZiNjMtNGVmZC04ZTEzLTM4NjM4NmQzNWJlNyIsInBlcnNvbmEiOiJwYXlyb2xsX"
    cj = cj & "2FkbWluIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsImludGVudCI6InJldmlld19leGNlcHRpb25zIiwiZXZlbnQiOiJhbGVydC9DWUMtMjAyNi0wNUIiLCJleGNlcHRpb25faWRzIjpbIkVYQy0yMDI2LTA1Qi0wMDEiLCJFWEMtM"
    cj = cj & "jAyNi0wNUItMDAyIl19.x3tMhclDC2eYu-BqJh5a_Jao2H6WrXZaIbsQUfDgIYo&surface=teams""}]}"

    Dim html As String
    html = "<!DOCTYPE html><html><head><meta charset=""utf-8"">"
    html = html & "<script type=""application/adaptivecard+json"">" & vbCrLf
    html = html & cj & vbCrLf
    html = html & "</script>"
    html = html & "</head><body style=""font-family:Segoe UI,Arial,sans-serif;max-width:600px;color:#222"">"
    html = html & "<h2 style=""color:#c43d3d"">Payroll exceptions need your review</h2>"
    html = html & "<p>Acme Manufacturing - Pay period ending May 30, 2026 - 2 open exceptions, est. impact $2,087.50</p>"
    html = html & "<ul>"
    html = html & "<li><b>Joseph Smith</b> - Overtime variance high ($847.50)</li>"
    html = html & "<li><b>Sarah Lee</b> - PTO missing manager approval ($1,240.00)</li>"
    html = html & "</ul>"
    html = html & "<p><em>If your client does not render the Adaptive Card above, use the link below.</em></p>"
    html = html & "</body></html>"

    Dim msg As Outlook.MailItem
    Set msg = Application.CreateItem(olMailItem)
    msg.To = RECIPIENT
    msg.Subject = SUBJ
    msg.HTMLBody = html
    msg.Send

    MsgBox "Sent OAM test to " & RECIPIENT, vbInformation, "PayCycle"
End Sub
