Attribute VB_Name = "SendOamHtmlTest"
' Auto-generated by tests/generate-test-emails.py
' MODE B: Plain styled HTML email + 'Review' CTA only. Zero customer-side
' configuration required - works in any modern mail client.
'
' Import: Outlook -> Alt+F11 -> File > Import File... > SendOamHtmlTest.bas
' Run:    place cursor in SendOamHtmlTest, press F5.

Option Explicit

Public Sub SendOamHtmlTest()
    Const RECIPIENT As String = "james.nguyen@microsoft.com"
    Const SUBJ      As String = "[Test] HTML-only mode - payroll exceptions"

    Dim hb As String
    hb = ""
    hb = hb & "<body style=""margin:0;padding:0;background:#f5f6fa;font-family:Segoe UI,Arial,sans-serif;color:#222""><table role=""presentation"" cellspacing=""0"" cellpadding=""0"" border=""0"" width=""10"
    hb = hb & "0%"" style=""background:#f5f6fa;padding:24px 0""><tr><td align=""center""><table role=""presentation"" cellspacing=""0"" cellpadding=""0"" border=""0"" width=""640"" style=""max-width:640px;backgr"
    hb = hb & "ound:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08)""><tr><td style=""padding:24px 28px 0 28px""><div style=""color:#2667ff;font-size:12px;font-weight:6"
    hb = hb & "00;letter-spacing:.6px;text-transform:uppercase"">PayCycle Alert</div><h1 style=""margin:6px 0 0 0;font-size:22px;color:#1a1a1a;font-weight:600"">🔔 2 payroll exceptions need your revi"
    hb = hb & "ew</h1><div style=""color:#666;font-size:14px;margin-top:6px"">Acme Manufacturing · Pay period ending May 30, 2026</div></td></tr><tr><td style=""padding:18px 28px 0 28px""><p style=""m"
    hb = hb & "argin:0;font-size:14px;line-height:1.5;color:#333"">Your current pay cycle has 2 exceptions blocking submission. Review the details below and resolve them in Teams or the web app.</"
    hb = hb & "p></td></tr><tr><td style=""padding:18px 28px 0 28px""><table cellspacing=""0"" cellpadding=""0"" border=""0"" width=""100%"" style=""border:1px solid #ececec;border-radius:6px;overflow:hidde"
    hb = hb & "n""><thead><tr style=""background:#fafafa""><th style=""text-align:left;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-"
    hb = hb & "bottom:1px solid #ececec"">Employee</th><th style=""text-align:left;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-bo"
    hb = hb & "ttom:1px solid #ececec"">Issue</th><th style=""text-align:right;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-bottom"
    hb = hb & ":1px solid #ececec"">$ Impact</th></tr></thead><tbody><tr><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""font-weight:600;color:#222"">"
    hb = hb & "Joseph Smith</div>  <div style=""font-size:12px;color:#888;margin-top:2px"">EXC-2026-05B-001</div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"
    hb = hb & """>  <div style=""color:#222"">Overtime variance high</div>  <div style=""font-size:13px;color:#555;margin-top:4px;line-height:1.45"">14.5h OT vs 4h avg (261% over 6 periods).</div>  <d"
    hb = hb & "iv style=""margin-top:6px"">    <span style=""display:inline-block;background:#fff3cd;color:#664d03;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;letter-spacing:.3"
    hb = hb & "px"">WARNING</span></div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top;text-align:right;white-space:nowrap;font-weight:600;color:#222"">$847.50"
    hb = hb & "</td></tr><tr><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""font-weight:600;color:#222"">Sarah Lee</div>  <div style=""font-size:12px"
    hb = hb & ";color:#888;margin-top:2px"">EXC-2026-05B-002</div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""color:#222"">PTO missing manage"
    hb = hb & "r approval</div>  <div style=""font-size:13px;color:#555;margin-top:4px;line-height:1.45"">3 days PTO 2026-05-25..27, no approver action.</div>  <div style=""margin-top:6px"">    <span"
    hb = hb & " style=""display:inline-block;background:#cfe2ff;color:#084298;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;letter-spacing:.3px"">INFO</span></div></td><td style"
    hb = hb & "=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top;text-align:right;white-space:nowrap;font-weight:600;color:#222"">$1,240.00</td></tr></tbody></table></td></tr>"
    hb = hb & "<tr><td style=""padding:18px 28px 0 28px""><div style=""background:#fff3cd;color:#664d03;padding:10px 14px;border-radius:6px;font-size:13px;border-left:3px solid #ffc107"">⏰ <strong>Cy"
    hb = hb & "cle deadline:</strong> 2026-05-30 17:00 PT</div></td></tr><tr><td style=""padding:22px 28px 28px 28px""><a href=""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontaine"
    hb = hb & "rapps.io/cta/handoff?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiaGFuZG9mZiIsInN1YiI6ImphbWVzLm5ndXllbkBtaWNyb3NvZnQuY29tIiwiaWF0IjoxNzc5MjEzODYxLCJleHAiOjE3NzkzMDAy"
    hb = hb & "NjEsImp0aSI6IjU0ZDQyZDgwLTE4MjItNDMwYi04OWY5LWRkMmEyNDBhMWUxMiIsInBlcnNvbmEiOiJwYXlyb2xsX2FkbWluIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsImludGVudCI6InJldmlld19leGNlcHRpb25zIiwiZXZl"
    hb = hb & "bnQiOiJhbGVydC9DWUMtMjAyNi0wNUIiLCJleGNlcHRpb25faWRzIjpbIkVYQy0yMDI2LTA1Qi0wMDEiLCJFWEMtMjAyNi0wNUItMDAyIl19.040EjPnV1Xpr5hspKRG9skwVBpqHey_xciy4Fvv4BRs&surface=teams"" style=""displ"
    hb = hb & "ay:inline-block;background:#2667ff;color:#ffffff;padding:11px 22px;border-radius:6px;text-decoration:none;font-family:Segoe UI,Arial,sans-serif;font-size:14px;font-weight:600"">💬 Re"
    hb = hb & "view with PayCycle Assistant</a></td></tr><tr><td style=""padding:0 28px 24px 28px""><hr style=""border:none;border-top:1px solid #ececec;margin:0 0 12px 0""><div style=""font-size:11px"
    hb = hb & ";color:#999;line-height:1.5"">Automated message from PayCycle. The CTA opens a Teams chat where the assistant has loaded all batch context for this email.</div></td></tr></table></t"
    hb = hb & "d></tr></table></body>"

    Dim html As String
    html = "<!DOCTYPE html><html><head><meta charset=""utf-8""></head>" & hb & "</html>"

    Dim msg As Outlook.MailItem
    Set msg = Application.CreateItem(olMailItem)
    msg.To = RECIPIENT
    msg.Subject = SUBJ
    msg.HTMLBody = html
    msg.Send

    MsgBox "Sent HTML-only test to " & RECIPIENT, vbInformation, "Test sender"
End Sub
