Attribute VB_Name = "SendOamCardTest"
' Auto-generated by tests/generate-test-emails.py
' MODE A: Adaptive Card (script tag in <head>) + rich HTML body fallback.
' For tenants with the full Outlook Actionable Messages provider configured.
'
' Import: Outlook -> Alt+F11 -> File > Import File... > SendOamCardTest.bas
' Run:    place cursor in SendOamCardTest, press F5.

Option Explicit

Public Sub SendOamCardTest()
    Const RECIPIENT As String = "james.nguyen@microsoft.com"
    Const SUBJ      As String = "[Test] Actionable Card mode - payroll exceptions"

    Dim cj As String
    cj = ""
    cj = cj & "{""type"":""AdaptiveCard"",""$schema"":""http://adaptivecards.io/schemas/adaptive-card.json"",""version"":""1.5"",""originator"":""45278df3-83dd-4167-86a2-b91b96395cc9"",""hideOriginalBody"":false,"""
    cj = cj & "body"":[{""type"":""TextBlock"",""text"":""Payroll exceptions need your review"",""size"":""Large"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""Acme Manufacturing - Pay period en"
    cj = cj & "ding May 30, 2026"",""isSubtle"":true,""wrap"":true,""spacing"":""None""},{""type"":""FactSet"",""spacing"":""Medium"",""facts"":[{""title"":""Cycle"",""value"":""Pay period ending May 30, 2026""},{""title"":"""
    cj = cj & "Deadline"",""value"":""2026-05-30 17:00 PT""},{""title"":""Open exceptions"",""value"":""2""},{""title"":""Estimated impact"",""value"":""$2,087.50""}]},{""type"":""Container"",""style"":""warning"",""spacing"":"
    cj = cj & """Medium"",""items"":[{""type"":""TextBlock"",""text"":""Joseph Smith - Overtime variance high"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""14.5h OT vs 4h avg (261% over 6 peri"
    cj = cj & "ods)."",""wrap"":true,""spacing"":""Small""},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.Http"",""title"":""\u2705 Approve"",""method"":""POST"",""url"":""https://payroll-m365-de"
    cj = cj & "mo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/oam/approve-exception/EXC-2026-05B-001"",""body"":"""",""headers"":[{""name"":""Content-Type"",""value"":""application/json""}]},{""type"""
    cj = cj & ":""Action.Http"",""title"":""\ud83d\udea9 Flag for HR"",""method"":""POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/oam/flag-exception/EXC-20"
    cj = cj & "26-05B-001"",""body"":"""",""headers"":[{""name"":""Content-Type"",""value"":""application/json""}]}]}]},{""type"":""Container"",""style"":""accent"",""spacing"":""Medium"",""items"":[{""type"":""TextBlock"",""text"
    cj = cj & """:""Sarah Lee - PTO missing manager approval"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""3 days PTO 2026-05-25..27, no approver action."",""wrap"":true,""spacing"":""Small"
    cj = cj & """},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.Http"",""title"":""\u2705 Approve"",""method"":""POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.az"
    cj = cj & "urecontainerapps.io/cta/oam/approve-exception/EXC-2026-05B-002"",""body"":"""",""headers"":[{""name"":""Content-Type"",""value"":""application/json""}]},{""type"":""Action.Http"",""title"":""\ud83d\udea"
    cj = cj & "9 Flag for HR"",""method"":""POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/oam/flag-exception/EXC-2026-05B-002"",""body"":"""",""headers"":[{"""
    cj = cj & "name"":""Content-Type"",""value"":""application/json""}]}]}]}],""actions"":[{""type"":""Action.OpenUrl"",""title"":""Review with PayCycle Assistant"",""url"":""https://payroll-m365-demo.politeground-c"
    cj = cj & "0ea36c5.eastus2.azurecontainerapps.io/cta/handoff?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiaGFuZG9mZiIsInN1YiI6ImphbWVzLm5ndXllbkBtaWNyb3NvZnQuY29tIiwiaWF0IjoxNzc"
    cj = cj & "5MjEzODYxLCJleHAiOjE3NzkzMDAyNjEsImp0aSI6ImE5NTUyZmUwLWE5ZWItNDA5OS05MjU5LTNiZDRkYWVkOTRjYSIsInBlcnNvbmEiOiJwYXlyb2xsX2FkbWluIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsImludGVudCI6InJ"
    cj = cj & "ldmlld19leGNlcHRpb25zIiwiZXZlbnQiOiJhbGVydC9DWUMtMjAyNi0wNUIiLCJleGNlcHRpb25faWRzIjpbIkVYQy0yMDI2LTA1Qi0wMDEiLCJFWEMtMjAyNi0wNUItMDAyIl19.GywAdixbrheelHKj8r2UgljCdeQJ4Zsjqtx3zFD_SG"
    cj = cj & "E&surface=teams""}]}"

    Dim hb As String
    hb = ""
    hb = hb & "<body style=""margin:0;padding:0;background:#f5f6fa;font-family:Segoe UI,Arial,sans-serif;color:#222""><table role=""presentation"" cellspacing=""0"" cellpadding=""0"" border=""0"" width=""10"
    hb = hb & "0%"" style=""background:#f5f6fa;padding:24px 0""><tr><td align=""center""><table role=""presentation"" cellspacing=""0"" cellpadding=""0"" border=""0"" width=""640"" style=""max-width:640px;backgr"
    hb = hb & "ound:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08)""><tr><td style=""padding:24px 28px 0 28px""><div style=""color:#2667ff;font-size:12px;font-weight:6"
    hb = hb & "00;letter-spacing:.6px;text-transform:uppercase"">PayCycle Alert</div><h1 style=""margin:6px 0 0 0;font-size:22px;color:#1a1a1a;font-weight:600"">🔔 2 payroll exceptions need your revi"
    hb = hb & "ew</h1><div style=""color:#666;font-size:14px;margin-top:6px"">Acme Manufacturing · Pay period ending May 30, 2026</div></td></tr><tr><td style=""padding:18px 28px 0 28px""><p style=""m"
    hb = hb & "argin:0;font-size:14px;line-height:1.5;color:#333"">Your current pay cycle has 2 exceptions blocking submission. Review the details below and resolve them in Teams or the web app.</"
    hb = hb & "p></td></tr><tr><td style=""padding:18px 28px 0 28px""><table cellspacing=""0"" cellpadding=""0"" border=""0"" width=""100%"" style=""border:1px solid #ececec;border-radius:6px;overflow:hidde"
    hb = hb & "n""><thead><tr style=""background:#fafafa""><th style=""text-align:left;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-"
    hb = hb & "bottom:1px solid #ececec"">Employee</th><th style=""text-align:left;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-bo"
    hb = hb & "ttom:1px solid #ececec"">Issue</th><th style=""text-align:right;padding:10px 12px;font-size:12px;color:#666;font-weight:600;letter-spacing:.3px;text-transform:uppercase;border-bottom"
    hb = hb & ":1px solid #ececec"">$ Impact</th></tr></thead><tbody><tr><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""font-weight:600;color:#222"">"
    hb = hb & "Joseph Smith</div>  <div style=""font-size:12px;color:#888;margin-top:2px"">EXC-2026-05B-001</div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"
    hb = hb & """>  <div style=""color:#222"">Overtime variance high</div>  <div style=""font-size:13px;color:#555;margin-top:4px;line-height:1.45"">14.5h OT vs 4h avg (261% over 6 periods).</div>  <d"
    hb = hb & "iv style=""margin-top:6px"">    <span style=""display:inline-block;background:#fff3cd;color:#664d03;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;letter-spacing:.3"
    hb = hb & "px"">WARNING</span></div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top;text-align:right;white-space:nowrap;font-weight:600;color:#222"">$847.50"
    hb = hb & "</td></tr><tr><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""font-weight:600;color:#222"">Sarah Lee</div>  <div style=""font-size:12px"
    hb = hb & ";color:#888;margin-top:2px"">EXC-2026-05B-002</div></td><td style=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top"">  <div style=""color:#222"">PTO missing manage"
    hb = hb & "r approval</div>  <div style=""font-size:13px;color:#555;margin-top:4px;line-height:1.45"">3 days PTO 2026-05-25..27, no approver action.</div>  <div style=""margin-top:6px"">    <span"
    hb = hb & " style=""display:inline-block;background:#cfe2ff;color:#084298;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;letter-spacing:.3px"">INFO</span></div></td><td style"
    hb = hb & "=""padding:14px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top;text-align:right;white-space:nowrap;font-weight:600;color:#222"">$1,240.00</td></tr></tbody></table></td></tr>"
    hb = hb & "<tr><td style=""padding:18px 28px 0 28px""><div style=""background:#fff3cd;color:#664d03;padding:10px 14px;border-radius:6px;font-size:13px;border-left:3px solid #ffc107"">⏰ <strong>Cy"
    hb = hb & "cle deadline:</strong> 2026-05-30 17:00 PT</div></td></tr><tr><td style=""padding:22px 28px 28px 28px""><a href=""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontaine"
    hb = hb & "rapps.io/cta/handoff?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjoiaGFuZG9mZiIsInN1YiI6ImphbWVzLm5ndXllbkBtaWNyb3NvZnQuY29tIiwiaWF0IjoxNzc5MjEzODYxLCJleHAiOjE3NzkzMDAy"
    hb = hb & "NjEsImp0aSI6IjU0ZDQyZDgwLTE4MjItNDMwYi04OWY5LWRkMmEyNDBhMWUxMiIsInBlcnNvbmEiOiJwYXlyb2xsX2FkbWluIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsImludGVudCI6InJldmlld19leGNlcHRpb25zIiwiZXZl"
    hb = hb & "bnQiOiJhbGVydC9DWUMtMjAyNi0wNUIiLCJleGNlcHRpb25faWRzIjpbIkVYQy0yMDI2LTA1Qi0wMDEiLCJFWEMtMjAyNi0wNUItMDAyIl19.040EjPnV1Xpr5hspKRG9skwVBpqHey_xciy4Fvv4BRs&surface=teams"" style=""displ"
    hb = hb & "ay:inline-block;background:#2667ff;color:#ffffff;padding:11px 22px;border-radius:6px;text-decoration:none;font-family:Segoe UI,Arial,sans-serif;font-size:14px;font-weight:600"">💬 Re"
    hb = hb & "view with PayCycle Assistant</a></td></tr><tr><td style=""padding:0 28px 24px 28px""><hr style=""border:none;border-top:1px solid #ececec;margin:0 0 12px 0""><div style=""font-size:11px"
    hb = hb & ";color:#999;line-height:1.5"">Automated message from PayCycle. The CTA opens a Teams chat where the assistant has loaded all batch context for this email.</div></td></tr></table></t"
    hb = hb & "d></tr></table></body>"

    Dim html As String
    html = "<!DOCTYPE html><html><head><meta charset=""utf-8"">" & _
           "<script type=""application/adaptivecard+json"">" & cj & "</script>" & _
           "</head>" & hb & "</html>"

    Dim msg As Outlook.MailItem
    Set msg = Application.CreateItem(olMailItem)
    msg.To = RECIPIENT
    msg.Subject = SUBJ
    msg.HTMLBody = html
    msg.Send

    MsgBox "Sent CARD-mode test to " & RECIPIENT, vbInformation, "Test sender"
End Sub
