Attribute VB_Name = "SendOamTest"
' Auto-generated by tests/generate-oam-test-bas.py
' Per-row Approve / Flag buttons + footer "Review with PayCycle Assistant".
'
' Import: Outlook -> Alt+F11 -> File > Import File... > SendOamTest.bas
' Run:    Place cursor in SendOamTest, press F5.

Option Explicit

Public Sub SendOamTest()
    Const RECIPIENT As String = "admin@MngEnvMCAP683110.onmicrosoft.com"
    Const SUBJ      As String = "PayCycle OAM test - per-row Approve / Flag actions"

    Dim cj As String
cj = ""
    cj = cj & "{""type"":""AdaptiveCard"",""$schema"":""http://adaptivecards.io/schemas/adaptive-card.json"",""version"":""1.5"",""originator"":""817b732b-ff83-462a-ba2e-fcc58c9b3b3c"",""hideOriginalBody"":false,"""
    cj = cj & "body"":[{""type"":""TextBlock"",""text"":""Payroll exceptions need your review"",""size"":""Large"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""Acme Manufacturing - Pay period en"
    cj = cj & "ding May 30, 2026"",""isSubtle"":true,""wrap"":true,""spacing"":""None""},{""type"":""FactSet"",""spacing"":""Medium"",""facts"":[{""title"":""Cycle"",""value"":""Pay period ending May 30, 2026""},{""title"":"""
    cj = cj & "Deadline"",""value"":""2026-05-30 17:00 PT""},{""title"":""Open exceptions"",""value"":""2""},{""title"":""Estimated impact"",""value"":""$2,087.50""}]},{""type"":""Container"",""style"":""warning"",""spacing"":"
    cj = cj & """Medium"",""items"":[{""type"":""TextBlock"",""text"":""Joseph Smith - Overtime variance high"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""EXC-2026-05B-001 - 14.5h OT vs 4h av"
    cj = cj & "g (261% over 6 periods). Impact $847.50."",""wrap"":true,""spacing"":""Small""},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.Http"",""title"":""\u2705 Approve"",""method"":""P"
    cj = cj & "OST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/oam/approve-exception/EXC-2026-05B-001"",""body"":"""",""headers"":[{""name"":""Content-Type"",""v"
    cj = cj & "alue"":""application/json""}]},{""type"":""Action.Http"",""title"":""\ud83d\udea9 Flag for HR"",""method"":""POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerap"
    cj = cj & "ps.io/cta/oam/flag-exception/EXC-2026-05B-001"",""body"":"""",""headers"":[{""name"":""Content-Type"",""value"":""application/json""}]}]}]},{""type"":""Container"",""style"":""accent"",""spacing"":""Medium"""
    cj = cj & ",""items"":[{""type"":""TextBlock"",""text"":""Sarah Lee - PTO missing manager approval"",""weight"":""Bolder"",""wrap"":true},{""type"":""TextBlock"",""text"":""EXC-2026-05B-002 - 3 days PTO 2026-05-25."
    cj = cj & ".27, no approver action. Impact $1,240.00."",""wrap"":true,""spacing"":""Small""},{""type"":""ActionSet"",""spacing"":""Small"",""actions"":[{""type"":""Action.Http"",""title"":""\u2705 Approve"",""method"":"
    cj = cj & """POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/oam/approve-exception/EXC-2026-05B-002"",""body"":"""",""headers"":[{""name"":""Content-Type"","
    cj = cj & """value"":""application/json""}]},{""type"":""Action.Http"",""title"":""\ud83d\udea9 Flag for HR"",""method"":""POST"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainer"
    cj = cj & "apps.io/cta/oam/flag-exception/EXC-2026-05B-002"",""body"":"""",""headers"":[{""name"":""Content-Type"",""value"":""application/json""}]}]}]}],""actions"":[{""type"":""Action.OpenUrl"",""title"":""Review "
    cj = cj & "with PayCycle Assistant"",""url"":""https://payroll-m365-demo.politeground-c0ea36c5.eastus2.azurecontainerapps.io/cta/handoff?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdXJwb3NlIjo"
    cj = cj & "iaGFuZG9mZiIsInN1YiI6ImphbWVzLm5ndXllbkBtaWNyb3NvZnQuY29tIiwiaWF0IjoxNzc5MTU3NDE3LCJleHAiOjE3NzkyNDM4MTcsImp0aSI6IjgyY2YzOTA2LTA1ZTgtNDQyMy05YjAzLTA1NTkyNDZmMDk5OCIsInBlcnNvbmEiOiJ"
    cj = cj & "wYXlyb2xsX2FkbWluIiwiYmF0Y2hfaWQiOiJCQVRDSC0yMDI2LTA1QiIsImludGVudCI6InJldmlld19leGNlcHRpb25zIiwiZXZlbnQiOiJhbGVydC9DWUMtMjAyNi0wNUIiLCJleGNlcHRpb25faWRzIjpbIkVYQy0yMDI2LTA1Qi0wMDE"
    cj = cj & "iLCJFWEMtMjAyNi0wNUItMDAyIl19.Y8zj7wPKe842MkE8ZJz4pUf4TXxHvW1dEfQTDxGmeSk&surface=teams""}]}"

    Dim html As String
    html = "<!DOCTYPE html><html><head><meta charset=""utf-8"">"
    html = html & "<script type=""application/adaptivecard+json"">" & vbCrLf
    html = html & cj & vbCrLf
    html = html & "</script>"
    html = html & "</head><body style=""font-family:Segoe UI,Arial,sans-serif;max-width:600px;color:#222"">"
    html = html & "<h2 style=""color:#c43d3d"">Payroll exceptions need your review</h2>"
    html = html & "<p>Acme Manufacturing - Pay period ending May 30, 2026 - 2 open exceptions, est. impact $2,087.50</p>"
    html = html & "<ul>"
    html = html & "<li><b>Joseph Smith</b> - Overtime variance high ($847.50)</li>"
    html = html & "<li><b>Sarah Lee</b> - PTO missing manager approval ($1,240.00)</li>"
    html = html & "</ul>"
    html = html & "<p><em>If your client does not render the Adaptive Card above, use the link below.</em></p>"
    html = html & "</body></html>"

    Dim msg As Outlook.MailItem
    Set msg = Application.CreateItem(olMailItem)
    msg.To = RECIPIENT
    msg.Subject = SUBJ
    msg.HTMLBody = html
    msg.Send

    MsgBox "Sent OAM test to " & RECIPIENT, vbInformation, "PayCycle"
End Sub
